### ISSUE TITLE
PyInquirer issue

### ISSUE THREAD

**Issue by 4h1g4L0w4** [Nwqda/Sweet-Pineapple-Builder#2]
hello, i have this issue when i try run the program

sudo python3 sweetPineappleBuilder.py
Traceback (most recent call last):
  File "/home/augusto/Sweet-Pineapple-Builder/sweetPineappleBuilder.py", line 11, in <module>
    from PyInquirer import Separator, Token, prompt, style_from_dict
  File "/usr/local/lib/python3.10/dist-packages/PyInquirer/__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/key_binding/bindings/basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/styles/__init__.py", line 8, in <module>
    from .from_dict import *
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/styles/from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by Nwqda** [comment]
Hello,

To solve this bug you need to edit the file `vi /usr/local/lib/python3.10/dist-packages/prompt_toolkit/styles/from_dict.py` then replace line 9 `from collections import Mapping` by `from collections.abc import Mapping`. 

This should solve the error and make the script work.

**Comment by 4h1g4L0w4** [comment]
Thank you very much, that solved the problem.
